---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: realapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels: 
        app: nginx
    spec:
      containers:
      - name: nginx
        image: sravandevops95/realapp:v1
        ports:
        - containerPort: 80
...
