apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: realapp
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30006
